# Generated by Django 4.0.3 on 2022-08-09 16:57

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assassin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=100)),
                ('discordName', models.CharField(max_length=32, verbose_name='discord name')),
                ('discordTag', models.PositiveSmallIntegerField(verbose_name='discord tag')),
                ('subject', models.CharField(choices=[('ARC', 'UG - Archaeology and Anthropology'), ('BCM', 'UG - Biochemistry (Molecular and Cellular)'), ('BIO', 'UG - Biology'), ('BMS', 'UG - Biomedical Sciences'), ('CHM', 'UG - Chemistry'), ('CAR', 'UG - Classical Archaeology and Ancient History'), ('CLS', 'UG - Classics'), ('CLE', 'UG - Classics and English'), ('CLM', 'UG - Classics and Modern Languages'), ('CLO', 'UG - Classics and Oriental Studies'), ('CSC', 'UG - Computer Science'), ('CSP', 'UG - Computer Science and Philosophy'), ('ESC', 'UG - Earth Sciences (Geology)'), ('ECM', 'UG - Economics and Management'), ('ENG', 'UG - Engineering Science'), ('ELL', 'UG - English Language and Literature'), ('EML', 'UG - English and Modern Languages'), ('EME', 'UG - European and Middle Eastern Languages'), ('FAR', 'UG - Fine Art'), ('FCE', 'UG - Foundation Year (Chemistry, Engineering and Materials Science)'), ('FHU', 'UG - Foundation Year (Humanities)'), ('FLA', 'UG - Foundation Year (Law)'), ('FPP', 'UG - Foundation Year (PPE)'), ('GEO', 'UG - Geography'), ('HIS', 'UG - History'), ('HAM', 'UG - History (Ancient and Modern)'), ('HEC', 'UG - History and Economics'), ('HEN', 'UG - History and English'), ('HML', 'UG - History and Modern Languages'), ('HPO', 'UG - History and Politics'), ('HAR', 'UG - History of Art'), ('HSC', 'UG - Human Sciences'), ('LAW', 'UG - Law (Jurisprudence)'), ('MAS', 'UG - Materials Science'), ('MAT', 'UG - Mathematics'), ('MCS', 'UG - Mathematics and Computer Science'), ('MPH', 'UG - Mathematics and Philosophy'), ('MST', 'UG - Mathematics and Statistics'), ('MED', 'UG - Medicine'), ('MLA', 'UG - Modern Languages'), ('MLL', 'UG - Modern Languages and Linguistics'), ('MUS', 'UG - Music'), ('ORI', 'UG - Oriental Studies'), ('PHL', 'UG - Philosophy and Modern Languages'), ('PHE', 'UG - Philosophy, Politics and Economics (PPE)'), ('PHT', 'UG - Philosophy and Theology'), ('PHY', 'UG - Physics'), ('PHP', 'UG - Physics and Philosophy'), ('PSE', 'UG - Psychology (Experimental)'), ('PSP', 'UG - Psychology, Philosophy and Linguistics'), ('ROR', 'UG - Religion and Oriental Studies'), ('THR', 'UG - Theology and Religion'), ('PGD', 'PG - PGDip'), ('PGC', 'PG - PGCert'), ('BCL', 'PG - BCL'), ('BMB', 'PG - BM BCh'), ('DTP', 'PG - BBSRC DTP'), ('CDT', 'PG - EPSRC CDT'), ('MBA', 'PG - MBA'), ('MFA', 'PG - MFA'), ('MJR', 'PG - MJur'), ('MPH', 'PG - MPhil'), ('MPP', 'PG - MPP'), ('MSC', 'PG - MSc'), ('MST', 'PG - MSt'), ('MTH', 'PG - MTh'), ('DCP', 'PG - DClinPsych'), ('DEN', 'PG - DEng'), ('DPH', 'PG - DPhil')], max_length=3, verbose_name='subject')),
                ('college', models.CharField(choices=[('ALL', 'All Souls College'), ('BAL', 'Balliol College'), ('BLA', 'Blackfriars'), ('BRA', 'Brasenose College'), ('CAM', 'Campion Hall'), ('CHR', 'Christ Church'), ('COR', 'Corpus Christi College'), ('EXE', 'Exeter College'), ('GRE', 'Green Templeton College'), ('HAR', 'Harris Manchester College'), ('HER', 'Hertford College'), ('JES', 'Jesus College'), ('KEB', 'Keble College'), ('KEL', 'Kellogg College'), ('LMH', 'Lady Margaret Hall'), ('LNA', 'Linacre College'), ('LNC', 'Lincoln College'), ('MAG', 'Magdalen College'), ('MAN', 'Mansfield College'), ('MER', 'Merton College'), ('NEW', 'New College'), ('NUF', 'Nuffield College'), ('ORI', 'Oriel College'), ('PEM', 'Pembroke College'), ('QUE', "The Queen's College"), ('REG', "Regent's Park College"), ('REU', 'Reuben College'), ('SOM', 'Somerville College'), ('ANN', "St Anne's College"), ('ANT', "St Antony's College"), ('BEN', "St Benet's Hall"), ('CAT', "St Catherine's College"), ('CRO', 'St Cross College'), ('EDM', 'St Edmund Hall'), ('HIL', "St Hilda's College"), ('HUG', "St Hugh's College"), ('JOH', "St John's College"), ('PET', "St Peter's College"), ('STE', "St Stephen's House"), ('TRI', 'Trinity College'), ('UNI', 'University College'), ('WAD', 'Wadham College'), ('WOL', 'Wolfson College'), ('WOR', 'Worcester College'), ('WYC', 'Wycliffe Hall')], max_length=3, verbose_name='college')),
                ('startYear', models.PositiveSmallIntegerField(verbose_name='matriculated')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('room', models.CharField(max_length=256, verbose_name='room number')),
                ('postal', models.CharField(blank=True, max_length=256, verbose_name='postal address')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('request_pay', models.BooleanField(default=False, verbose_name='reqp')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('assassin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.assassin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
