# Generated by Django 4.0.3 on 2022-08-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assassin',
            name='cabal',
            field=models.CharField(blank=True, choices=[('MAS', 'Guildmaster'), ('TRE', 'Treasurer'), ('ARC', 'Archivist'), ('SEC', 'Secretary'), ('WEB', 'Webmaster'), ('MIN', 'Minister')], max_length=3, null=True, verbose_name='cabal role'),
        ),
    ]
