# Generated by Django 4.0.3 on 2022-07-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_assassin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assassin',
            name='address',
            field=models.CharField(blank=True, max_length=256, verbose_name='term time address'),
        ),
        migrations.AlterField(
            model_name='assassin',
            name='startYear',
            field=models.PositiveSmallIntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
