# Generated by Django 4.0.3 on 2022-07-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registered',
        ),
        migrations.AddField(
            model_name='user',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='paid'),
        ),
    ]
