# Generated by Django 4.0.3 on 2022-07-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='request',
            new_name='payRequest',
        ),
    ]
