# Generated by Django 4.0.3 on 2022-07-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_request_user_payrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='payRequest',
            new_name='request_pay',
        ),
    ]
