# Generated by Django 4.0.3 on 2022-07-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_payrequest_user_request_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='assassin',
            name='postal',
            field=models.CharField(blank=True, max_length=256, verbose_name='(optional) postal address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_pay',
            field=models.BooleanField(default=False, verbose_name='reqp'),
        ),
    ]
