# Generated by Django 4.0.3 on 2022-08-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_assassin_postal_alter_user_request_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cabal',
            field=models.BooleanField(default=False, verbose_name='is cabal'),
        ),
    ]
