# Generated by Django 4.0.3 on 2022-08-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_cabal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cabal',
        ),
    ]
