# Generated by Django 4.0.3 on 2022-08-05 17:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0014_remove_user_cabal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=100, verbose_name='config name')),
                ('allowed_melee', models.BooleanField(default=True, verbose_name='allow melee')),
                ('allowed_thrown', models.BooleanField(default=True, verbose_name='allow thrown')),
                ('allowed_ranged', models.BooleanField(default=True, verbose_name='allow ranged')),
                ('allowed_animal', models.BooleanField(default=True, verbose_name='allow attack animal')),
                ('allowed_costume', models.BooleanField(default=True, verbose_name='allow costume')),
                ('points_melee', models.PositiveSmallIntegerField(default=10, verbose_name='melee points')),
                ('points_thrown', models.PositiveSmallIntegerField(default=5, verbose_name='thrown points')),
                ('points_ranged', models.PositiveSmallIntegerField(default=5, verbose_name='ranged points')),
                ('points_animal', models.PositiveSmallIntegerField(default=10, verbose_name='animal points')),
                ('points_costume', models.PositiveSmallIntegerField(default=10, verbose_name='costume points')),
                ('allowed_normal', models.BooleanField(default=True, verbose_name='allow normal')),
                ('allowed_raid', models.BooleanField(default=True, verbose_name='allow raids')),
                ('allowed_duel', models.BooleanField(default=True, verbose_name='allow duels')),
                ('points_normal', models.PositiveSmallIntegerField(default=0, verbose_name='normal bonus points')),
                ('points_raid', models.PositiveSmallIntegerField(default=0, verbose_name='raid bonus points')),
                ('points_duel', models.PositiveSmallIntegerField(default=0, verbose_name='duel bonus points')),
                ('allowed_indirect', models.BooleanField(default=True, verbose_name='allow indirect')),
                ('points_indirect', models.PositiveSmallIntegerField(default=10, verbose_name='indirect points')),
                ('respawn_count', models.PositiveSmallIntegerField(default=32767, verbose_name='respawn count')),
                ('respawn_time', models.DurationField(default=datetime.timedelta(seconds=21600), verbose_name='respawn time')),
                ('respawn_start', models.BooleanField(default=True, verbose_name='global respawn on start')),
                ('respawn_end', models.BooleanField(default=True, verbose_name='global respawn on end')),
                ('respawn_delay', models.DurationField(default=datetime.timedelta(seconds=1800), verbose_name='end respawn delay')),
                ('protect_flags', models.BooleanField(default=False, verbose_name='prevent flag transfers')),
            ],
        ),
        migrations.CreateModel(
            name='EventScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_start', models.DurationField(default=datetime.timedelta(0), verbose_name='event start offset')),
                ('event_duration', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='event duration')),
                ('event_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.configscript')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='flag name')),
                ('visibility', models.CharField(choices=[('EVR', 'Everyone'), ('SHR', 'Shared'), ('HID', 'Hidden')], default='EVR', max_length=3, verbose_name='flag visibility')),
                ('friendly', models.BooleanField(default=False, verbose_name='flag friendly')),
                ('allowed_melee', models.BooleanField(default=True, verbose_name='melee kills allowed')),
                ('allowed_thrown', models.BooleanField(default=True, verbose_name='thrown kills allowed')),
                ('allowed_ranged', models.BooleanField(default=True, verbose_name='ranged kills allowed')),
                ('allowed_animal', models.BooleanField(default=True, verbose_name='animal kills allowed')),
                ('allowed_costume', models.BooleanField(default=True, verbose_name='costume kills allowed')),
                ('multiplier_melee', models.FloatField(default=1, verbose_name='melee kill multiplier')),
                ('multiplier_thrown', models.FloatField(default=1, verbose_name='thrown kill multiplier')),
                ('multiplier_ranged', models.FloatField(default=1, verbose_name='ranged kill multiplier')),
                ('multiplier_animal', models.FloatField(default=1, verbose_name='animal kill multiplier')),
                ('multiplier_costume', models.FloatField(default=1, verbose_name='costume kill multiplier')),
                ('bonus_melee', models.FloatField(default=0, verbose_name='melee kill bonus')),
                ('bonus_thrown', models.FloatField(default=0, verbose_name='thrown kill bonus')),
                ('bonus_ranged', models.FloatField(default=0, verbose_name='ranged kill bonus')),
                ('bonus_animal', models.FloatField(default=0, verbose_name='animal kill bonus')),
                ('bonus_costume', models.FloatField(default=0, verbose_name='costume kill bonus')),
                ('allowed_normal', models.BooleanField(default=True, verbose_name='melee kills allowed')),
                ('allowed_raid', models.BooleanField(default=True, verbose_name='thrown kills allowed')),
                ('allowed_duel', models.BooleanField(default=True, verbose_name='ranged kills allowed')),
                ('multiplier_normal', models.FloatField(default=1, verbose_name='normal kill multiplier')),
                ('multiplier_raid', models.FloatField(default=1, verbose_name='raid kill multiplier')),
                ('multiplier_duel', models.FloatField(default=1, verbose_name='duel kill multiplier')),
                ('bonus_raid', models.FloatField(default=0, verbose_name='raid kill bonus')),
                ('bonus_normal', models.FloatField(default=0, verbose_name='normal kill bonus')),
                ('bonus_duel', models.FloatField(default=0, verbose_name='duel kill bonus')),
                ('allowed_indirect', models.BooleanField(default=True, verbose_name='indirect kills allowed')),
                ('multiplier_indirect', models.FloatField(default=1, verbose_name='indirect kill multiplier')),
                ('bonus_indirect', models.FloatField(default=0, verbose_name='indirect kill bonus')),
                ('on_kill', models.CharField(choices=[('KNP', 'Keep'), ('LNP', 'Lose'), ('KAP', 'Keep and Pass'), ('LAP', 'Lose and Pass')], default='KNP', max_length=3, verbose_name='flag action on kill')),
                ('on_death', models.CharField(choices=[('KNP', 'Keep'), ('LNP', 'Lose'), ('KAP', 'Keep and Pass'), ('LAP', 'Lose and Pass')], default='KNP', max_length=3, verbose_name='flag action on death')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='game title')),
                ('description', models.TextField(verbose_name='game description')),
                ('game_start', models.DateTimeField(verbose_name='game start')),
                ('game_duration', models.DurationField(default=datetime.timedelta(days=7), verbose_name='game duration')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', models.BooleanField(default=False, verbose_name='is player alive')),
                ('game_respawns', models.PositiveSmallIntegerField(verbose_name='game respawns')),
                ('event_respawns', models.PositiveSmallIntegerField(verbose_name='event respawns')),
                ('next_respawn', models.DateTimeField(verbose_name='next respawn')),
                ('assassin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.assassin')),
                ('flags', models.ManyToManyField(to='games.flag', verbose_name='player flags')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='IndirectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=256, verbose_name='trap location')),
                ('date_set', models.DateTimeField(auto_now=True, verbose_name='trap laid')),
                ('date_sprung', models.DateTimeField(blank=True, null=True, verbose_name='trap sprung')),
                ('trapper_report', models.TextField(blank=True, null=True, verbose_name='trapper report')),
                ('target_report', models.TextField(blank=True, null=True, verbose_name='target report')),
                ('trap_sprung', models.BooleanField(default=False, verbose_name='trap successful')),
                ('trap_successful', models.BooleanField(default=False, verbose_name='trap successful')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traps_recieved', to='games.player')),
                ('trapper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traps_set', to='games.player')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=256, verbose_name='kill location')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='kill date')),
                ('report_text', models.TextField(verbose_name='killer report')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.player')),
            ],
        ),
        migrations.CreateModel(
            name='GameScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_scripts', models.ManyToManyField(to='games.eventscript')),
                ('primary_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.configscript')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.gamescript'),
        ),
        migrations.CreateModel(
            name='DirectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(choices=[('MEL', 'Melee'), ('THR', 'Thrown'), ('RNG', 'Ranged'), ('ATK', 'Attack Animal'), ('COS', 'Costume')], default='MEL', max_length=3, verbose_name='kill weapon')),
                ('context', models.CharField(choices=[('NOR', 'Normal'), ('RAD', 'Raid'), ('DUL', 'Duel')], default='NOR', max_length=3, verbose_name='kill context')),
                ('location', models.CharField(max_length=256, verbose_name='kill location')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='kill date')),
                ('killer_report', models.TextField(blank=True, null=True, verbose_name='killer report')),
                ('victim_report', models.TextField(blank=True, null=True, verbose_name='victim report')),
                ('killer_validated', models.BooleanField(default=False, verbose_name='killer validated')),
                ('victim_validated', models.BooleanField(default=False, verbose_name='victim validated')),
                ('killer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kills', to='games.player')),
                ('victim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deaths', to='games.player')),
            ],
        ),
    ]
