# Generated by Django 4.0.3 on 2022-08-12 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventscript',
            name='event_duration',
            field=models.DurationField(verbose_name='event duration'),
        ),
        migrations.AlterField(
            model_name='eventscript',
            name='event_start',
            field=models.DurationField(verbose_name='event start offset'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='friendly',
            field=models.BooleanField(default=False, verbose_name='friendly'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_duration',
            field=models.DurationField(verbose_name='game duration'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_start',
            field=models.DateTimeField(verbose_name='game start'),
        ),
        migrations.AlterField(
            model_name='game',
            name='xas_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.xasgroup'),
        ),
        migrations.CreateModel(
            name='InfoLore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('text', models.TextField(verbose_name='info or lore')),
                ('release_start', models.DurationField(verbose_name='release start')),
                ('release_end', models.DurationField(verbose_name='release end')),
                ('public', models.BooleanField(verbose_name='visible to all')),
                ('flags', models.ManyToManyField(to='games.flag', verbose_name='visible to')),
                ('xas_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.xasgroup')),
            ],
        ),
        migrations.AddField(
            model_name='gamescript',
            name='info_lore_releases',
            field=models.ManyToManyField(to='games.infolore'),
        ),
    ]
