# Generated by Django 4.0.3 on 2022-08-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_eventscript_event_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infolore',
            name='public',
            field=models.BooleanField(default=True, verbose_name='visible to all'),
        ),
    ]
