# Generated by Django 4.0.3 on 2022-08-13 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_infolore_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescript',
            name='report_bounty',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='bounty for late reports'),
        ),
        migrations.AddField(
            model_name='gamescript',
            name='report_deadline',
            field=models.DurationField(default=datetime.timedelta(seconds=43200), verbose_name='report confirmation deadline'),
        ),
        migrations.CreateModel(
            name='PlayerBounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='bonus')),
                ('date_given', models.DateTimeField(auto_now_add=True, verbose_name='date given')),
                ('date_claimed', models.DateTimeField(blank=True, null=True, verbose_name='date claimed')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimed_bounties', to='games.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounties', to='games.player')),
            ],
        ),
    ]
