# Generated by Django 4.0.3 on 2022-08-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_published_gamescript_flags_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescript',
            name='event_scripts',
            field=models.ManyToManyField(blank=True, to='games.eventscript'),
        ),
        migrations.AlterField(
            model_name='gamescript',
            name='flags_used',
            field=models.ManyToManyField(blank=True, to='games.flag'),
        ),
        migrations.AlterField(
            model_name='gamescript',
            name='info_lore_releases',
            field=models.ManyToManyField(blank=True, to='games.infolore'),
        ),
        migrations.AlterField(
            model_name='infolore',
            name='flags',
            field=models.ManyToManyField(blank=True, to='games.flag', verbose_name='visible to'),
        ),
        migrations.AlterField(
            model_name='player',
            name='flags',
            field=models.ManyToManyField(blank=True, to='games.flag', verbose_name='player flags'),
        ),
    ]
