# Generated by Django 4.0.3 on 2022-08-19 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_gamescript_event_scripts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directreport',
            name='kill_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='kill date'),
        ),
        migrations.AlterField(
            model_name='flagbonus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date given'),
        ),
        migrations.AlterField(
            model_name='generalreport',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='report date'),
        ),
        migrations.AlterField(
            model_name='indirectreport',
            name='date_set',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='trap laid'),
        ),
        migrations.AlterField(
            model_name='playerbonus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date given'),
        ),
    ]
